name: easy home

# 좋아 가보자3

on:
  push:
    branches:
      - main
      - feat-docker

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 17 설치
      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 빌드 (API Gateway)
      - name: 빌드 (API Gateway)
        working-directory: ./api-gateway
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          pwd
          ls
          ls ./build/libs

      # 3. 빌드 (Eureka Server)
      - name: 빌드 (Eureka Server)
        working-directory: ./eureka-server
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          pwd
          ls
          ls ./build/libs

      # 3. 빌드 (msa-sb-user)
      - name: 빌드 (msa-sb-user)
        working-directory: ./msa-sb-user
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          pwd
          ls
          ls ./build/libs

      # 3. 빌드 (redis-db-test)
      - name: 빌드 (redis-db-test)
        working-directory: ./redis-db-test
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          pwd
          ls
          ls ./build/libs

      - name: 빌드 (easy-home-vote)
        working-directory: ./easy-home-vote
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          pwd
          ls
          ls ./build/libs

      - name: 빌드 (easy-home-survey)
        working-directory: ./easy-home-survey
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          pwd
          ls
          ls ./build/libs
          
          

      # 5. SSH를 통해 EC2에 연결하여 업로드
      - name: EC2에 연결하여 업로드 (유레카, gateway, msa-user, redis)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ./eureka-server/build/libs/eureka-server-0.0.1-SNAPSHOT.jar, ./api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar, ./msa-sb-user/build/libs/msa-sb-user-0.0.1-SNAPSHOT.jar, ./redis-db-test/build/libs/redis-db-test-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/demo/home

      - name: EC2에 연결하여 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: ./easy-home-vote/build/libs/easy-home-vote-0.0.1-SNAPSHOT.jar, ./easy-home-survey/build/libs/easy-home-survey-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/demo/home

      - name: EC2에서 업로드된 파일 확인
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            ls -l /home/ubuntu/demo/home/eureka-server/build/libs/
            ls -l /home/ubuntu/demo/home/api-gateway/build/libs/
            ls -l /home/ubuntu/demo/home/msa-sb-user/build/libs/
            ls -l /home/ubuntu/demo/home/redis-db-test/build/libs/
            ls -l /home/ubuntu/demo/home/easy-home-vote/build/libs/
            ls -l /home/ubuntu/demo/home/easy-home-survey/build/libs/

      - name: MySQL 연결 확인
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            export MYSQL_USER=${{ secrets.MYSQL_USER }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            
            mysql -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "SHOW DATABASES;"
            echo "MySQL connection successful."

      - name: 컨테이너 실행 확인 및 시작
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker ps -a
            sudo docker start redis-db

      - name: 서버 접속
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/server/easy_home
            mkdir -p /home/ubuntu/server/easy_home
            mv /home/ubuntu/demo/home/eureka-server/build/libs/eureka-server-0.0.1-SNAPSHOT.jar /home/ubuntu/server/easy_home/eureka-server-0.0.1-SNAPSHOT.jar
            mv /home/ubuntu/demo/home/api-gateway/build/libs/api-gateway-0.0.1-SNAPSHOT.jar /home/ubuntu/server/easy_home/api-gateway-0.0.1-SNAPSHOT.jar
            mv /home/ubuntu/demo/home/msa-sb-user/build/libs/msa-sb-user-0.0.1-SNAPSHOT.jar /home/ubuntu/server/easy_home/msa-sb-user-0.0.1-SNAPSHOT.jar
            mv /home/ubuntu/demo/home/redis-db-test/build/libs/redis-db-test-0.0.1-SNAPSHOT.jar /home/ubuntu/server/easy_home/redis-db-test-0.0.1-SNAPSHOT.jar
            mv /home/ubuntu/demo/home/easy-home-vote/build/libs/easy-home-vote-0.0.1-SNAPSHOT.jar /home/ubuntu/server/easy_home/easy-home-vote-0.0.1-SNAPSHOT.jar
            mv /home/ubuntu/demo/home/easy-home-survey/build/libs/easy-home-survey-0.0.1-SNAPSHOT.jar /home/ubuntu/server/easy_home/easy-home-survey-0.0.1-SNAPSHOT.jar
            cd /home/ubuntu/server/easy_home
            
            # 깃 시크릿 사용
            export EC2_HOST=${{ secrets.EC2_HOST }}
            export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            export MYSQL_HOST=${{ secrets.MYSQL_HOST }}
            export MYSQL_USER=${{ secrets.MYSQL_USER }}
            export MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}
            export EMAIL_PASSWORD="${{ secrets.EMAIL_PASSWORD }}"
            
            source ~/.bashrc
            
            echo "EC2 Host: $EC2_HOST"
            echo "JWT_SECRET_KEY: $JWT_SECRET_KEY"
            echo "MySQL Host: $MYSQL_HOST"
            echo "MySQL User: $MYSQL_USER"
            echo "EMAIL_USERNAME: $EMAIL_USERNAME"
            echo "EMAIL_PASSWORD: $EMAIL_PASSWORD"
            
            sudo fuser -k -n tcp 8761 || true
            sudo fuser -k -n tcp 8080 || true
            sudo fuser -k -n tcp 8081 || true
            sudo fuser -k -n tcp 8090 || true
            sudo fuser -k -n tcp 8084 || true
            sudo fuser -k -n tcp 8085 || true
            
            nohup java -jar eureka-server-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &
            nohup java -jar api-gateway-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &
            nohup java -jar redis-db-test-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &
            nohup java -jar msa-sb-user-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &
            nohup java -jar easy-home-survey-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &
            nohup java -jar easy-home-vote-0.0.1-SNAPSHOT.jar > ./output.log 2>&1 &
            


